# Site Configuration
title: "Gianluigi Calcaterra"
email: gianluigi.calcaterra@gmail.com
description: >-
  Welcome to my personal website. This is a place where I share my thoughts,
  projects, and experiences.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://calca.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Local theme - no remote theme needed

# Reading Files
include:
  - .htaccess

# Site Author
author:
  name: "Gianluigi Calcaterra"
  avatar: "/assets/images/avatar.jpg"
  bio: "Mobile App Developer specializing in iOS and Android applications. Passionate about creating intuitive user experiences and solving complex technical challenges."
  location: "Italy"
  job_title: "Mobile App Developer"
  links:
    - label: "GitHub"
      icon: "ri-github-line"
      url: "https://github.com/calca"
    - label: "LinkedIn"
      icon: "ri-linkedin-line"
      url: "https://linkedin.com/in/gianluigi-calcaterra"
    - label: "App Store"
      icon: "ri-app-store-line" 
      url: "https://apps.apple.com/developer/gianluigi-calcaterra/id123456"
    - label: "Email"
      icon: "ri-mail-line"
      url: "mailto:gianluigi.calcaterra@gmail.com"

# Defaults
defaults: []

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
