# Site Configuration
title: "Gianluigi Calcaterra"
email: gianluigi.calcaterra@gmail.com
description: >-
  My my personal website. This is a place where I share my projects and experiences.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://calca.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Local theme - no remote theme needed

# Reading Files
include:
  - .htaccess

# Site Author
author:
  name: "calca"
  avatar: "/assets/images/avatar.jpg"
  bio: "Welcome to my personal space"
  location: "Milan"
  links:
    - label: "GitHub"
      icon: "ri-github-line"
      url: "https://github.com/calca"
    - label: "Instagram"
      icon: "ri-instagram-line"
      url: "https://www.instagram.com/calca80"
    - label: "Buy Me a Coffee"
      icon: "ri-cup-line"
      url: "https://www.buymeacoffee.com/gianluigick"
    - label: "Email"
      icon: "ri-mail-line"
      url: "mailto:gianluigi.calcaterra@gmail.com"

# Defaults
defaults: []

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
