# Site Configuration
title: "Calca's Personal Website"
email: calca@example.com
description: >-
  Welcome to my personal website. This is a place where I share my thoughts,
  projects, and experiences.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://calca.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Theme settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Reading Files
include:
  - .htaccess
  - _pages

# Site Author
author:
  name: "Calca"
  avatar: "/assets/images/avatar.jpg"
  bio: "Welcome to my personal space on the web"
  location: "Somewhere on Earth"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/calca"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/